import Head from 'next/head'
import styles from '../styles/Home.module.css'
import VisPheno from '../components/visPheno'
import Header from '../components/header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>dataVis</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>
      <VisPheno/>
    </div>
  )
}
